from handlers.command_handlers.lowprice import command_lowprice
from handlers.command_handlers.highprice import command_highprice
from handlers.command_handlers.bestdeal import command_bestdeal
from handlers.command_handlers.history import command_history
